name: Daily Commit

on:
  schedule:
    - cron: "0 22 * * *"  # 6:00 AM PHT (10:00 PM UTC)
    - cron: "0 4 * * *"    # 12:00 PM PHT (4:00 AM UTC)
    - cron: "0 5 * * *"    # 1:00 PM PHT (5:00 AM UTC)
    - cron: "0 10 * * *"   # 6:00 PM PHT (10:00 AM UTC)

  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update daily log file
        run: |
          echo "Last commit: $(date)" > daily-log.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add daily-log.txt
          git commit -m "Automated commit: $(date)"
          git push
