name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 3 * * *'    # runs once daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate language chart
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/languages.svg
        hide-keys: general, contributions, repositories
        max-languages: 10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
